#!/bin/bash

if [ -f CMakeCache.txt ]
then
  rm CMakeCache.txt
fi

if [ -d CMakeFiles ]
then
  rm -rf CMakeFiles
fi

if [ -f cmake_install.cmake ]
then
  rm cmake_install.cmake
fi

if [ -f Makefile ]
then
  rm Makefile
fi

if [ -f a.out ]
then
  rm a.out
fi

if [ -f exe ]
then
  rm exe
fi

exit 0

