#!/bin/bash

## declare an array variable
declare -a arr=( animation CMakeLists.txt collision enemy game gameState gameStateMachine health hero hud inputHandler jsonLoader main playState position projectile scenary sprite structs target textures transitionState values vector dataLevel1.json dataMain.json )

arr=( CMakeLists.txt game glWindow inputHandler main playState shader triangle.vs triangle.fs )

if [ $HOSTNAME == "arch" ]
then
  syscall="gedit "
else
  syscall="xed "
fi

for i in "${arr[@]}"
do
   #echo "$i"
   if [ -e "$i.hpp" ]; then
     syscall+="$i.hpp "
   fi
   
   if [ -e "$i.cpp" ]; then
     syscall+="$i.cpp "
   fi
   
   if [ -e "$i" ]; then
     if [ $i != game ]; then
       syscall+="$i "
     fi
   fi
   
   if [ -e "shaders/$i" ]; then
     syscall+="shaders/$i "
   fi
   
   
done

echo $syscall
eval $syscall &

exit 0
