#!/bin/sh

useHUD=1
fullscreen=0

let cores=`grep -c ^processor /proc/cpuinfo`

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $SCRIPT_DIR/..
PROJECT_DIR=$PWD

cd $PROJECT_DIR || exit 1

if [[ $# -gt 0 ]]; then
  if [[ $1 == "clean" ]]; then
    if [[ -d build ]]; then
      rm -rf build
    fi
  fi
fi

if [[ ! -d build ]]; then
  mkdir build
fi

cd build || exit 1

# copy the assets into the build directory
if [[ -d $PROJECT_DIR/src/res ]]; then
  rsync -rav $PROJECT_DIR/src/res $PROJECT_DIR/build
  #cp -R $PROJECT_DIR/src/res/ ./
fi
if [[ -d $PROJECT_DIR/src/assets ]]; then
  rsync -rav $PROJECT_DIR/src/assets $PROJECT_DIR/build
  #cp -R  $PROJECT_DIR/src/assets ./
fi

clear

cmake .. || exit 1

if [[ $cores -gt 1 ]]
then
  make -j${cores} || exit 1
else
  make || exit 1
fi

command=""

if [[ $useHUD -eq 1 ]]
then
  command+='GALLIUM_HUD=".dfps;cpu0+cpu1+cpu2+cpu3;GPU-load;VRAM-usage" '
fi

command+='./exe'

if [[ fullscreen -eq 1 ]]
then
  command+=' --fullscreen'
fi

eval $command

exit 0

