#!/bin/bash

let cores=`grep -c ^processor /proc/cpuinfo`

useHUD=1
fullscreen=1

clear

cmake . || exit 1

if [[ $cores -gt 1 ]]
then
  make -j${cores} || exit 1
else
  make || exit 1
fi

command=""

if [[ $useHUD -eq 1 ]]
then
  command+='GALLIUM_HUD=".dfps;cpu0+cpu1+cpu2+cpu3;GPU-load;VRAM-usage" '
fi

command+='./exe'

if [[ fullscreen -eq 1 ]]
then
  command+=' --fullscreen'
fi

eval $command

exit 0
